### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by markstos** [itchyny/github-migrator#1]
To reproduce, try importing the `bergie/passport-saml` repo to another empty repo on Github. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x69a399]

goroutine 1 [running]:
github.com/itchyny/github-migrator/migrator.groupEventsByCreated(0xc00008eea0, 0x4, 0x4, 0xc0002351c0, 0x702a60, 0xc0002351a0)
        /home/mark/RAgit/github-migrator/migrator/builder_events.go:75 +0x1b9
github.com/itchyny/github-migrator/migrator.(*builder).buildImportEventComments(0xc0004a1980, 0xc0000fb280, 0x4, 0x4, 0x6d54c0, 0xc0002771c0)
        /home/mark/RAgit/github-migrator/migrator/builder_events.go:15 +0x92
github.com/itchyny/github-migrator/migrator.(*builder).buildImportComments(0xc0004a1980, 0xc000182870, 0x9dd528, 0x0, 0x0, 0xc000130e38)
        /home/mark/RAgit/github-migrator/migrator/builder.go:151 +0x72
github.com/itchyny/github-migrator/migrator.(*builder).build(0xc0004a1980, 0x0, 0x77, 0x77)
        /home/mark/RAgit/github-migrator/migrator/builder.go:71 +0x1c7
github.com/itchyny/github-migrator/migrator.(*migrator).buildImport(0xc00020fd60, 0xc0004b4340, 0xc0003a5cc0, 0xc0000fafe0, 0x4, 0x4, 0xc00008eea0, 0x4, 0x4, 0xc00012e270, ...)
        /home/mark/RAgit/github-migrator/migrator/builder.go:43 +0x190
github.com/itchyny/github-migrator/migrator.(*migrator).migrateIssue(0xc00020fd60, 0xc0004b4340, 0xc0004a1d20, 0x0, 0x0, 0x0, 0x0)
        /home/mark/RAgit/github-migrator/migrator/issues.go:136 +0x8d8
github.com/itchyny/github-migrator/migrator.(*migrator).migrateIssues(0xc00020fd60, 0x0, 0x0)
        /home/mark/RAgit/github-migrator/migrator/issues.go:42 +0x1bc
github.com/itchyny/github-migrator/migrator.(*migrator).Migrate(0xc00020fd60, 0x14, 0x7fff11f4f169)
        /home/mark/RAgit/github-migrator/migrator/migrator.go:71 +0x2fa
main.run(0xc000114160, 0x2, 0x2, 0x44316a, 0x971fe0)
        /home/mark/RAgit/github-migrator/main.go:31 +0x96
main.main()
        /home/mark/RAgit/github-migrator/main.go:17 +0x6c
```

**Comment by markstos** [comment]
The issue is reproducible. When re-running the script, it skips a bunch of work with "already done" messages and then crashes at the  same point:

```
<=== 200 OK: GET: https://api.github.com/users/ghost
===> GET: https://api.github.com/users/bergie
<=== 200 OK: GET: https://api.github.com/users/bergie
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x69a399]

goroutine 1 [running]:
github.com/itchyny/github-migrator/migrator.groupEventsByCreated(0xc000242940, 0x4, 0x4, 0xc000243300, 0x702a60, 0xc0002432c0)
        /home/mark/RAgit/github-migrator/migrator/builder_events.go:75 +0x1b9
gi
```

**Comment by markstos** [comment]
Root case appears that `getEventUser()` can return `nil` in some some cases, but the code currently assumes this would never happen and crashes.

**Comment by itchyny** [comment]
Can you paste the issue number?

**Comment by markstos** [comment]
@itchyny I'm not sure what you mean. There is only one issue and it is this issue, issue #1.

**Comment by markstos** [comment]
I'm attempting a patch now, but I'm learning Go at the same time, so results may be mixed.

**Comment by itchyny** [comment]
Which issue in bergie/passport-saml causes the panic?

**Comment by markstos** [comment]
I can't see that in the output. I looked for a `debug` or `verbose` option and didn't see one. The last user mentioned is `bergie`, the original author and project owner.

**Comment by markstos** [comment]
I have `admin` access on the repo, but not `owner` access, if that makes a difference.

**Comment by markstos** [comment]
This patch helped get past the immediate error, but it crashes later at a different point in the code, apparently due to another lack of `nil` checking. 

```
diff --git a/migrator/builder_events.go b/migrator/builder_events.go
index 302810a..9b6fa2a 100644
--- a/migrator/builder_events.go
+++ b/migrator/builder_events.go
@@ -72,7 +72,8 @@ func groupEventsByCreated(xs []*github.Event) [][]*github.Event {
        for _, x := range xs {
                var appended bool
                for i, es := range ess {
-                       if getEventUser(es[0]).Login == getEventUser(x).Login &&
+                       if getEventUser(es[0]) != nil &&
+        getEventUser(es[0]).Login == getEventUser(x).Login &&
                                nearTime(es[0].CreatedAt, x.CreatedAt) &&
                                eventGroupTypes[es[0].Event] == eventGroupTypes[x.Event] {
                                ess[i] = append(ess[i], x)
```

I'm looking at the second case now.

**Comment by markstos** [comment]
Here's the second issue:

```
<=== 404 Not Found: GET: https://api.github.com/users/Herbert%20Voj%C4%8D%C3%ADk
```
The name is "Herbert Vojčík ".

That doesn't look like a Github username to me.

This may be a different kind of bug.

**Comment by markstos** [comment]
I only find "Herbert Vojčík" mentioned in the package.json. I can't find any other mentions in the project, nor any user on Github that matches that name.

**Comment by itchyny** [comment]
It seems that still fails due to https://github.com/bergie/passport-saml/pull/15/commits/3ba015843757bde81127b30bf2ec27250c0f773d.

**Comment by markstos** [comment]
Yes, I confirm it fixes the first failure I ran into, but there's another. I'll open a new issue for it.
