### ISSUE TITLE
fails due to deleted Github user

### ISSUE THREAD

**Issue by markstos** [itchyny/github-migrator#2]
Example commit which triggers it:

https://github.com/bergie/passport-saml/commit/3ba015843757bde81127b30bf2ec27250c0f773d

Example of what output looks like when the the failure is triggered:

```
===> GET: https://api.github.com/users/Herbert%20Voj%C4%8D%C3%ADk
<=== 404 Not Found: GET: https://api.github.com/users/Herbert%20Voj%C4%8D%C3%ADk
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x698452]

goroutine 1 [running]:
github.com/itchyny/github-migrator/migrator.(*builder).buildImageTag(0xc0000a9980, 0x0, 0x23, 0xc0001dbf08, 0x0)
        /home/mark/RAgit/github-migrator/migrator/builder.go:240 +0x42
github.com/itchyny/github-migrator/migrator.(*builder).buildUserActionBody(0xc0000a9980, 0x0, 0x74fd1a, 0x27, 0x0, 0x0, 0x0, 0x0)
        /home/mark/RAgit/github-migrator/migrator/builder.go:234 +0x75
```

**Comment by itchyny** [comment]
This is fixed as well.

**Comment by markstos** [comment]
Thank you so much. This tool is very helpful. Testing now.

**Comment by markstos** [comment]
It seems to be running smoothly now. I'm going to get something to eat and will check to see if it's finished later.
